<h1>02장 Numpy 소개</h1>

<h2>NumPy 배열 연산 : 유니버설 함수</h2>

<b>루프는 느리다</b>

In [113]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size = 5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [115]:
big_array = np.random.randint(1, 100, size=100)
%timeit compute_reciprocals(big_array)

191 µs ± 901 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


<b>UFincs 소개</b>  <br>
벡터화 연산은 간단히 배열에 연산을 수행해 각 요소에 적용함으로써 수행하는 것. <br>
백터화 방식은 루프를 NumPy의 기저를 이루는 컴파일된 계층으로 밀어 넣음으로써 훨씬 빠르게 실행되도록 설계됐다.</p>

In [117]:
print(compute_reciprocals(values))
print(1.0/values)


[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [118]:
%timeit (1.0/ big_array)

1.2 µs ± 16.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [119]:
np.arange(5) / np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [121]:
x = np.arange(9).reshape((3,3))
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

<p>ufunc를 통한 벡터화를 이용한 연산은 파이썬 루프를 통해 구현된 연산보다 대부분 더 효율적이며, 특히 배열의 크기가 커질수록 그 차이가 확연해진다.<br>
<p>


<B>NumPy 유니버설 함수(UFuncs)</B>


<b>배열 산술 연산</b>

In [8]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2) 
print("x / 2 =", x / 2) 
print("x // 2 =", x // 2) #바닥 나눗셈(나머지는 버림) 

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [9]:
print("-x      =", -x)
print("x ** 2  =", x ** 2)
print("x % 2 = ", x % 2)

-x      = [ 0 -1 -2 -3]
x ** 2  = [0 1 4 9]
x % 2 =  [0 1 0 1]


In [10]:
-(0.5 * x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [11]:
np.add(x, 2)

array([2, 3, 4, 5])

<b>표2-2 표준 NumPy 데이터 타입</b>
<table style="width:100%">
  <tr>
    <th>연산자</th>
    <th>대응 ufuncs</th> 
    <th>설명</th>
  </tr>
  <tr>
    <td>+</td>
    <td>np.add</td> 
    <td>덧셈(예: 1 + 1 = 2)</td>
  </tr>
  <tr>
    <td>-</td>
    <td>np.subtract</td> 
    <td>뺄셈(예: 3 - 2 = 1)</td>
  </tr>
  <tr>
    <td>-</td>
    <td>np.negative</td> 
    <td>단항 음수(예: -2)</td>
  </tr>
  <tr>
    <td>\*</td>
    <td>np.multiply</td> 
    <td>곱셈(예: 2 * 3 = 6)</td>
  </tr>
  <tr>
    <td>/</td>
    <td>np.divide</td> 
    <td>나눗셈(예: 3 / 2 = 1.5)</td>
  </tr>
  <tr>
    <td>//</td>
    <td>np.floor_divide</td> 
    <td>바닥 나눗셈(예: 3 // 2 = 1)</td>
  </tr>
  <tr>
    <td>\*\*</td>
    <td>np.power</td> 
    <td>지수 연산(예: 2 ** 3 = 8)</td>
  </tr>
  <tr>
    <td>/</td>
    <td>np.mod</td> 
    <td>나머지 연산(예: 9 % 4 = 1)</td>
  </tr>
</table>

<b>절대값 함수</b>

In [13]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [17]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [18]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [20]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

<b>삼각함수</b>

In [21]:
theta = np.linspace(0, np.pi, 3)

In [24]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("con(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
con(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [27]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x)) 

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


<b>지수와 로그</b>

In [31]:
x = [1,2,3]
print("x    =", x)
print("e^x  =", np.exp(x))
print("2^x  =", np.exp2(x))
print("3^x  =", np.power(3,x))

x    = [1, 2, 3]
e^x  = [ 2.71828183  7.3890561  20.08553692]
2^x  = [2. 4. 8.]
3^x  = [ 3  9 27]


In [32]:
x = [1,2,4,10]
print("x        =", x)
print("ln(x)   =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
log(x)   = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [33]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x)  -1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x)  -1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


<b>특화된 유니버설 함수</b>

In [35]:
from scipy import special
# 감마 함수(일반화 된 계승)와 관련 함수
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x,2) =", special.beta(x,2))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x,2) = [0.5        0.03333333 0.00909091]


In [38]:
#오차 함수(가우스 적분), 그 보수(complemnet)와 역수(inverse)
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x)   =", special.erf(x))
print("erfc(x)   =", special.erfc(x))
print("erfinv(x)   =", special.erfinv(x))

erf(x)   = [0.         0.32862676 0.67780119 0.84270079]
erfc(x)   = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x)   = [0.         0.27246271 0.73286908        inf]


<b>고급 Ufunc 기능</b>

<b>출력지정</b> 
<p>대규모 연산인 경우, 연산 결과를 저장할 배열을 지정하는 것이 유용할 때가 있음. <br>
임시 배열을 생성하지 않고 지정한 배열을 이용해 원하는 메모리 위치에 직접 연산 결과를 쓸 수 있음<p>

In [41]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out = y)
print(y)

[ 0. 10. 20. 30. 40.]


In [42]:
y = np.zeros(10)
np.power(2, x, out = y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


<b>집계</b> <br>
이항 ufuncs의 경우, 객체로부터 직접 연산을 할 수 있다.<br>
배열을 특정 연산으로 축소하고자 한다면, ufunc의 reduce 메서드를 사용한다.<br>
reduce는 결과가 하나만 남을 때까지 해당 연산을 배열 요소에 반복해서 적용한다.<br>

In [45]:
x = np.arange(1,6)
print(x)
np.add.reduce(x)

[1 2 3 4 5]


15

In [46]:
np.multiply.reduce(x)

120

In [49]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [50]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

연산의 경우, 결과를 계산하는 np.sum np.prod, np.cumsum, np.cumprod 도 있다.

<b>외적(Outer products)</b>

In [55]:
x = np.arange(1,6)
print(x)
np.multiply.outer(x, x)

[1 2 3 4 5]


array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

<b>Ufuncs: 더 알아보기</b>

참고<br>
http://www.numpy.org <br>
http://www.scipy.org 