<h1>02장 Numpy 소개</h1>

<h2> Numpy 배열의 기초</h2>

<b>배열 속성 지정</b> <br>
배열의 크기, 모양, 메모리 소시량, 데이터 타입을 결정한다.<br>
<b>배열 인덱싱</b><br>
개별 배열 요솟값을 가져오고 설정한다.<br>
<b>배열 슬라이싱</b><br>
큰 배열 내에 있는 작은 하위 배열을 가져오고 설정한다.<br>
<b>배열 재구조화</b><br>
해당 배열의 형상을 변경한다.<br>
<b>배열 결합 및 분할</b><br>
여러 배열을 하나로 결합하고 하나의 배열을 여러 개로 분할 한다.<br>

<b>NumPy 배열 속성 지정 </b>

In [3]:
import numpy as np
np.random.seed(0) #재현 가능성을 위한 시드 값

x1 = np.random.randint(10, size = 6)         # 1차원 배열
x2 = np.random.randint(10, size = (3, 4))    # 2차원 배열
x3 = np.random.randint(10, size = (3, 4, 5)) # 3차원 배열

In [5]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size) 

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [6]:
print("dtype:", x3.dtype)

dtype: int64


In [11]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


<b>배열 인덱싱 : 단일 요소에 접근하기</b>

In [12]:
x1

array([5, 0, 3, 3, 7, 9])

In [13]:
x1[0]

5

In [14]:
x1[4]

7

In [15]:
x1[-1]

9

In [16]:
x1[-2]

7

In [17]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [18]:
x2[0,0]

3

In [20]:
x2[2,0]

1

In [21]:
x2[2,-1]

7

In [22]:
x2[0,0] = 12

In [23]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

<p> 파이썬 리스트와 달리 NumPy 배열은 고정 타입을 가짐. 정ㅅ 배열에 부동 소수점을 삽입하려고 하면 그 값의 소수점 이하를 잘라버림</p>

In [25]:
x1[0] = 3.14159 # 이 값의 소수점 이하는 삭제함

In [26]:
x1

array([3, 0, 3, 3, 7, 9])

<b> 배열 슬라이딩: 하위 배열에 접근하기 </b> <br>
꺾쇠괄호를 사용해 개별 배열 요소에 접근할 수 있는 것처럼 콜론(:) 기호로 표시되는 슬라이스(slice) 표기법으로 하위 배열에 접근 가능<br>

<p>x[start:stop:step]</p>

In [30]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
x[:5]   # 처음부터 5개 요소

array([0, 1, 2, 3, 4])

In [37]:
x[5:]   # 인덱스 5 다음 요소들

array([5, 6, 7, 8, 9])

In [38]:
x[4:7]  # 중간 하위 배열

array([4, 5, 6])

In [39]:
x[::2]  # 하나 걸러 하나씩의 요소로 구성된 배열

array([0, 2, 4, 6, 8])

In [40]:
x[1::2] # 인덱스 1에서 시작해 하나 걸러 하나씩 요소로 구성된 배열

array([1, 3, 5, 7, 9])

In [41]:
x[::1]  # 모든 요소를 거꾸로 나열

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
x[5::-2] # 인덱스 5부터 하나 걸러 하나씩 요소를 거꾸로 나열

array([5, 3, 1])

<b> 다차원 하위 배열</b>

In [44]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [45]:
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [46]:
x2[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [47]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [51]:
print(x2[:, 0]) # x2의 첫번째 열

[12  7  1]


In [53]:
print(x2[0, :])

[12  5  2  4]


In [54]:
print(x2[0]) #x2[0, :]와 동일

[12  5  2  4]


<b>사본이 아닌 뷰로서의 하위 배열</b><br>
배열 슬라이스의 중요한 기능 중 하나는 배열 슬라이스가 배열 데이터의 사본(copy)가 아니라 뷰(view)를 반환한다는 점. 

In [55]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [58]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [59]:
x2_sub[0,0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [60]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


<p>큰 데이터 세트를 다룰 때, 기반 데이터 버퍼를 복사하지 않아도 이 데이터의 일부에 접근하고 처리 할 수 있음<p>

 <b>배열의 사본 만들기 / .copy()</b>

In [62]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [63]:
x2_sub_copy[0,0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [64]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [65]:
x2_sub_copy[0,0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [66]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


<b>배열 재구조화 / .reshape()</b>

In [68]:
grid = np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


<p> 이 코드가 동작하려면 초기 배열의 규보가 형상이 변경된 배열의 규모와 일치해야 한다.<br>
일반적인 재구조화 패턴은 1차원 배열을 2차원 행이나 열 매트릭스로 전환하는 것이며, reshape 로 하지 못하면, newaxis 키워드를 사용해 더 쉽게 처리할 수 있다.<p>

In [71]:
x = np.array([1,2,3]) 
# reshape을 이용한 행 벡터 
x.reshape((1,3))

array([[1, 2, 3]])

In [74]:
# newaxis를 이용한 행 벡터 
x[np.newaxis, :]

array([[1, 2, 3]])

In [76]:
# reshape를 이용한 열 벡터 
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [78]:
# newaxis를 이용한 열 벡터 
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

<b>배열 연결 및 분할</b><br>
<b>배열 연결/ np.concatenate, np.vstack, np.hstack</b>

In [80]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [81]:
z = [99,99,99]
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


In [83]:
grid = np.array([[1,2,3],
                [4,5,6]])
# 첫번 째 축을 따라 연결
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [84]:
# 두 번쨰 축을 따라 연결(0부터 시작하는 인덱스 방식)
np.concatenate([grid, grid], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [89]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],
               [6,5,4]])
# 배열을 수직으로 쌓음
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [90]:
# 배열을 수평으로 쌓음
y = np.array([[99],
            [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

<b>배열 분할 하기/ np.split np.hsplit np.vsplit</b>

In [96]:
x = [1,2,3,99,99,3,2,1]
x1, x2, x3 = np.split(x, [3,5]) # 분할 지점을 의미한다.
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [101]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [102]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower) 

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
left, right = np.hsplit(grid,[2])
print(left)
print(right) 

<p>비슷하게 np.dsplit 는 세번쨰 축을 따라 배열을 분할한다.</p>