In [6]:
import numpy

In [7]:
import numpy as np

<b>파이썬의 데이터 타입 이해하기</b>

<b>파이썬 정수는 정수 이상이다</b>

<p>ob_refcnt : 파이썬이 조용히 메모리 할당과 해제를 처리할 수 있게 돕는 참조 횟수 <br/>
ob_type : 변수 타입을 인코딩<br/>
ob_size : 다음 데이터 멤버의 크기를 지정<br/>
ob_digit : 파이썬 변수가 나타내는 실제 정숫값을 포함 </p>



<b>파이썬 리스트는 리스트 이상이다</b>

In [15]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
type(L[0])

int

In [18]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [19]:
type(L2[0])

str

In [23]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

<b>파이썬의 고정 타입 배열</b>

In [24]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
import numpy as np

<b> 파이썬 리스트에서 배열 만들기 </b>

In [26]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

파이썬 리스트와 달리 Numpy는 배열의 모든요소가 같은 타입이어야 함<br>
타입이 일치하지 않으면 가능한 경우, 상위 타입을 취함.

In [27]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [30]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [31]:
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

<b>처음부터 배열 만들기</b>

In [40]:
# 0으로 채운 길이 10의 정수 배열 만들기
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
# 1로 채운 3x5 부동 소수점 배열 만들기
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
# 3.14로 채운 3x5 배열 만들기
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [43]:
# 선형 수열로 채운 배열 만들기
# 0에서 시작해 2씨 더해 20까지 채움
# (내장 함수인 range()와 유사함)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [44]:
# 0과 1사이에 일정한 가격을 가진 다섯 개의 값으로 채운 배열 만들기
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [45]:
# 균등하게 분포된 3x3 배열 만들기
# 0과 1 사이의 난수로 채움
np.random.random((3,3))

array([[0.90948499, 0.75350208, 0.18918032],
       [0.47881734, 0.57420403, 0.43493193],
       [0.41515158, 0.94443408, 0.84059916]])

In [46]:
# 정규분포(평균=0, 표준편차=1)의 난수로 채운 3x3 배열 만들기
np.random.normal(0,1,(3,3))

array([[ 1.11879537, -0.40404905, -0.29227879],
       [-0.44099949,  0.88865515, -0.63987318],
       [-2.25976297,  0.90534681, -0.67478363]])

In [47]:
# [0,10] 구간의 임의의 정수로 채운 3x3 배열 만들기
np.random.randint(0, 10, (3,3))

array([[5, 2, 8],
       [6, 1, 2],
       [0, 4, 9]])

In [50]:
# 3x3 단위 행렬 만들기
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
# 세 개의 정수를 가지는 초기화되지 않은 배열 만들기
# 값은 해당 메모리 위치에 이미 존재하고 있는 값으로 채움
np.empty(3)

array([1., 1., 1.])

<b>Numpy 표준 데이터 타입</b>

In [53]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [54]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

<table style="margin-left: auto; margin-right: auto;>
    <thead>
        <tr>
            <th>데이터 타입</th>
            <th>설명</th>
        </tr>
    </thead>    
    <tbody>   
        <tr>
            <td>bool_</td>
            <td>1바이트로 저장된 부울 값(참 또는 거짓)</td>
        </tr>    
        <tr>
            <td>int_</td>
            <td>기본 정수 타입</td>
        </tr>    
        <tr>
            <td>intc</td>
            <td>C int와 동일</td>
        </tr>        
        <tr>
            <td>intp</td>
            <td>인덱싱에 사용하는 정수</td>
        </tr>   
        <tr>
            <td>int8</td>
            <td>정수(-128 ~ 127)</td>
        </tr>       
        <tr>
            <td>int16</td>
            <td>정수(-32768 ~ 32767)</td>
        </tr>       
        <tr>
            <td>int32</td>
            <td>정수(-214783648 ~ 214783647)</td>
        </tr>   
        <tr>
            <td>int64</td>
            <td>정수(-9223372036854775808 ~ 9223372036854775807)</td>
        </tr>    
        <tr>
            <td>uint8</td>
            <td>부호 없는 정수(0 ~ 255 )</td>
        </tr>    
        <tr>
            <td>unit16</td>
            <td>부호 없는 정수(0 ~ 65535 )</td>
        </tr>    
        <tr>
            <td>uint32</td>
            <td>부호 없는 정수(0 ~ 4294967295 )</td>
        </tr>    
        <tr>
            <td>uint64</td>
            <td>부호 없는 정수(0 ~ 18446744073709551615)</td>
        </tr>    
        <tr>
            <td>float_</td>
            <td>float64의 약칭</td>
        </tr> 
        <tr>
            <td>float16</td>
            <td>반정밀 부동 소수점: 부호 비트, 5비트 지수, 10비트 지수</td>
        </tr> 
        <tr>
            <td>float32</td>
            <td>단정밀 부동 소수점: 부호 비트, 8비트 지수, 23비트 지수</td>
        </tr> 
        <tr>
            <td>float64</td>
            <td>배정밀 부동 소수점: 부호 비트, 11비트 지수, 53비트 기수</td>
        </tr> 
        <tr>
            <td>complex_</td>
            <td>complex128의 약칭</td>
        </tr> 
        <tr>
            <td>complex64</td>
            <td>복소수, 두 개의 32비트 부동 소수점의 표현</td>
        </tr>
        <tr>
            <td>complex128</td>
            <td>복소수, 두 개의 64비트 부동 소수점의 표현</td>
        </tr>

    </tbody>    
</table>

<b> Numpy 배열의 기초 </b>

<b>배열 속성 지정</b> <br>
배열의 크기, 모양, 메모리 소시량, 데이터 타입을 결정한다.<br>
<b>배열 인덱싱</b><br>
개별 배열 요솟값을 가져오고 설정한다.<br>
<b>배열 슬라이싱</b><br>
큰 배열 내에 있는 작은 하위 배열을 가져오고 설정한다.<br>
<b>배열 재구조화</b><br>
해당 배열의 형상을 변경한다.<br>
<b>배열 결합 및 분할</b><br>
여러 배열을 하나로 결합하고 하나의 배열을 여러 개로 분할 한다.<br>


<b>NumPy 배열 속성 지정 </b>

In [3]:
import numpy as np
np.random.seed(0) #재현 가능성을 위한 시드 값

x1 = np.random.randint(10, size = 6)         # 1차원 배열
x2 = np.random.randint(10, size = (3, 4))    # 2차원 배열
x3 = np.random.randint(10, size = (3, 4, 5)) # 3차원 배열

In [5]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size) 

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [6]:
print("dtype:", x3.dtype)

dtype: int64


In [11]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


<b>배열 인덱싱 : 단일 요소에 접근하기</b>

In [12]:
x1

array([5, 0, 3, 3, 7, 9])

In [13]:
x1[0]

5

In [14]:
x1[4]

7

In [15]:
x1[-1]

9

In [16]:
x1[-2]

7

In [17]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [18]:
x2[0,0]

3

In [20]:
x2[2,0]

1

In [21]:
x2[2,-1]

7

In [22]:
x2[0,0] = 12

In [23]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

<p> 파이썬 리스트와 달리 NumPy 배열은 고정 타입을 가짐. 정ㅅ 배열에 부동 소수점을 삽입하려고 하면 그 값의 소수점 이하를 잘라버림</p>

In [25]:
x1[0] = 3.14159 # 이 값의 소수점 이하는 삭제함

In [26]:
x1

array([3, 0, 3, 3, 7, 9])

<b> 배열 슬라이딩: 하위 배열에 접근하기 </b> <br>
꺾쇠괄호를 사용해 개별 배열 요소에 접근할 수 있는 것처럼 콜론(:) 기호로 표시되는 슬라이스(slice) 표기법으로 하위 배열에 접근 가능<br>

<p>x[start:stop:step]</p>

In [30]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
x[:5]   # 처음부터 5개 요소

array([0, 1, 2, 3, 4])

In [37]:
x[5:]   # 인덱스 5 다음 요소들

array([5, 6, 7, 8, 9])

In [38]:
x[4:7]  # 중간 하위 배열

array([4, 5, 6])

In [39]:
x[::2]  # 하나 걸러 하나씩의 요소로 구성된 배열

array([0, 2, 4, 6, 8])

In [40]:
x[1::2] # 인덱스 1에서 시작해 하나 걸러 하나씩 요소로 구성된 배열

array([1, 3, 5, 7, 9])

In [41]:
x[::1]  # 모든 요소를 거꾸로 나열

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
x[5::-2] # 인덱스 5부터 하나 걸러 하나씩 요소를 거꾸로 나열

array([5, 3, 1])

<b> 다차원 하위 배열</b>

In [44]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [45]:
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [46]:
x2[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [47]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [51]:
print(x2[:, 0]) # x2의 첫번째 열

[12  7  1]


In [53]:
print(x2[0, :])

[12  5  2  4]


In [54]:
print(x2[0]) #x2[0, :]와 동일

[12  5  2  4]


<b>사본이 아닌 뷰로서의 하위 배열</b><br>
배열 슬라이스의 중요한 기능 중 하나는 배열 슬라이스가 배열 데이터의 사본(copy)가 아니라 뷰(view)를 반환한다는 점. 

In [55]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [58]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [59]:
x2_sub[0,0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [60]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


<p>큰 데이터 세트를 다룰 때, 기반 데이터 버퍼를 복사하지 않아도 이 데이터의 일부에 접근하고 처리 할 수 있음<p>

 <b>배열의 사본 만들기 / .copy()</b>

In [62]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [63]:
x2_sub_copy[0,0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [64]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [65]:
x2_sub_copy[0,0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [66]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


<b>배열 재구조화 / .reshape()</b>

In [68]:
grid = np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


<p> 이 코드가 동작하려면 초기 배열의 규보가 형상이 변경된 배열의 규모와 일치해야 한다.<br>
일반적인 재구조화 패턴은 1차원 배열을 2차원 행이나 열 매트릭스로 전환하는 것이며, reshape 로 하지 못하면, newaxis 키워드를 사용해 더 쉽게 처리할 수 있다.<p>

In [71]:
x = np.array([1,2,3]) 
# reshape을 이용한 행 벡터 
x.reshape((1,3))

array([[1, 2, 3]])

In [74]:
# newaxis를 이용한 행 벡터 
x[np.newaxis, :]

array([[1, 2, 3]])

In [76]:
# reshape를 이용한 열 벡터 
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [78]:
# newaxis를 이용한 열 벡터 
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

<b>배열 연결 및 분할</b><br>
<b>배열 연결/ np.concatenate, np.vstack, np.hstack</b>

In [80]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [81]:
z = [99,99,99]
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


In [83]:
grid = np.array([[1,2,3],
                [4,5,6]])
# 첫번 째 축을 따라 연결
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [84]:
# 두 번쨰 축을 따라 연결(0부터 시작하는 인덱스 방식)
np.concatenate([grid, grid], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [89]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],
               [6,5,4]])
# 배열을 수직으로 쌓음
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [90]:
# 배열을 수평으로 쌓음
y = np.array([[99],
            [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

<b>배열 분할 하기/ np.split np.hsplit np.vsplit</b>

In [96]:
x = [1,2,3,99,99,3,2,1]
x1, x2, x3 = np.split(x, [3,5]) # 분할 지점을 의미한다.
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [101]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [102]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower) 

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
left, right = np.hsplit(grid,[2])
print(left)
print(right) 

<p>비슷하게 np.dsplit 는 세번쨰 축을 따라 배열을 분할한다.</p>

<b>NumPy 배열 연산 : 유니버설 함수</b>

<b>루프는 느리다</b>

In [113]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size = 5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [115]:
big_array = np.random.randint(1, 100, size=100)
%timeit compute_reciprocals(big_array)

191 µs ± 901 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


<b>UFincs 소개</b>  <br>
벡터화 연산은 간단히 배열에 연산을 수행해 각 요소에 적용함으로써 수행하는 것. <br>
백터화 방식은 루프를 NumPy의 기저를 이루는 컴파일된 계층으로 밀어 넣음으로써 훨씬 빠르게 실행되도록 설계됐다.</p>

In [117]:
print(compute_reciprocals(values))
print(1.0/values)


[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [118]:
%timeit (1.0/ big_array)

1.2 µs ± 16.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [119]:
np.arange(5) / np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [121]:
x = np.arange(9).reshape((3,3))
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

<p>ufunc를 통한 벡터화를 이용한 연산은 파이썬 루프를 통해 구현된 연산보다 대부분 더 효율적이며, 특히 배열의 크기가 커질수록 그 차이가 확연해진다.<br>
<p>


In [ ]:
 ㄴ