<h1>02장 Numpy 소개</h1>

<h2>파이썬의 데이터 타입 이해하기</h2>

In [4]:
import numpy

In [5]:
import numpy as np

<b>파이썬 정수는 정수 이상이다</b>

<p>ob_refcnt : 파이썬이 조용히 메모리 할당과 해제를 처리할 수 있게 돕는 참조 횟수 <br/>
ob_type : 변수 타입을 인코딩<br/>
ob_size : 다음 데이터 멤버의 크기를 지정<br/>
ob_digit : 파이썬 변수가 나타내는 실제 정숫값을 포함 </p>



<b>파이썬 리스트는 리스트 이상이다</b>

In [15]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
type(L[0])

int

In [18]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [19]:
type(L2[0])

str

In [23]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

<b>파이썬의 고정 타입 배열</b>

In [24]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
import numpy as np

<b> 파이썬 리스트에서 배열 만들기 </b>

In [26]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

파이썬 리스트와 달리 Numpy는 배열의 모든요소가 같은 타입이어야 함<br>
타입이 일치하지 않으면 가능한 경우, 상위 타입을 취함.

In [27]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [30]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [31]:
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

<b>처음부터 배열 만들기</b>

In [40]:
# 0으로 채운 길이 10의 정수 배열 만들기
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
# 1로 채운 3x5 부동 소수점 배열 만들기
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
# 3.14로 채운 3x5 배열 만들기
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [43]:
# 선형 수열로 채운 배열 만들기
# 0에서 시작해 2씨 더해 20까지 채움
# (내장 함수인 range()와 유사함)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [44]:
# 0과 1사이에 일정한 가격을 가진 다섯 개의 값으로 채운 배열 만들기
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [45]:
# 균등하게 분포된 3x3 배열 만들기
# 0과 1 사이의 난수로 채움
np.random.random((3,3))

array([[0.90948499, 0.75350208, 0.18918032],
       [0.47881734, 0.57420403, 0.43493193],
       [0.41515158, 0.94443408, 0.84059916]])

In [46]:
# 정규분포(평균=0, 표준편차=1)의 난수로 채운 3x3 배열 만들기
np.random.normal(0,1,(3,3))

array([[ 1.11879537, -0.40404905, -0.29227879],
       [-0.44099949,  0.88865515, -0.63987318],
       [-2.25976297,  0.90534681, -0.67478363]])

In [47]:
# [0,10] 구간의 임의의 정수로 채운 3x3 배열 만들기
np.random.randint(0, 10, (3,3))

array([[5, 2, 8],
       [6, 1, 2],
       [0, 4, 9]])

In [50]:
# 3x3 단위 행렬 만들기
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
# 세 개의 정수를 가지는 초기화되지 않은 배열 만들기
# 값은 해당 메모리 위치에 이미 존재하고 있는 값으로 채움
np.empty(3)

array([1., 1., 1.])

<b>Numpy 표준 데이터 타입</b>

In [53]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [54]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

<table style="width:100%">
    <tr>
        <th>데이터 타입</th>
        <th>설명</th>
    </tr>   
    <tr>
        <td>bool_</td>
        <td>1바이트로 저장된 부울 값(참 또는 거짓)</td>
    </tr>    
    <tr>
        <td>int_</td>
        <td>기본 정수 타입</td>
    </tr>    
    <tr>
        <td>intc</td>
        <td>C int와 동일</td>
    </tr>        
    <tr>
        <td>intp</td>
        <td>인덱싱에 사용하는 정수</td>
    </tr>   
    <tr>
        <td>int8</td>
        <td>정수(-128 ~ 127)</td>
    </tr>       
    <tr>
        <td>int16</td>
        <td>정수(-32768 ~ 32767)</td>
    </tr>       
    <tr>
        <td>int32</td>
        <td>정수(-214783648 ~ 214783647)</td>
    </tr>   
    <tr>
        <td>int64</td>
        <td>정수(-9223372036854775808 ~ 9223372036854775807)</td>
    </tr>    
    <tr>
        <td>uint8</td>
        <td>부호 없는 정수(0 ~ 255 )</td>
    </tr>    
    <tr>
        <td>unit16</td>
        <td>부호 없는 정수(0 ~ 65535 )</td>
    </tr>    
    <tr>
        <td>uint32</td>
        <td>부호 없는 정수(0 ~ 4294967295 )</td>
    </tr>    
    <tr>
        <td>uint64</td>
        <td>부호 없는 정수(0 ~ 18446744073709551615)</td>
    </tr>    
    <tr>
        <td>float_</td>
        <td>float64의 약칭</td>
    </tr> 
    <tr>
        <td>float16</td>
        <td>반정밀 부동 소수점: 부호 비트, 5비트 지수, 10비트 지수</td>
    </tr> 
    <tr>
        <td>float32</td>
        <td>단정밀 부동 소수점: 부호 비트, 8비트 지수, 23비트 지수</td>
    </tr> 
    <tr>
        <td>float64</td>
        <td>배정밀 부동 소수점: 부호 비트, 11비트 지수, 53비트 기수</td>
    </tr> 
    <tr>
        <td>complex_</td>
        <td>complex128의 약칭</td>
    </tr> 
    <tr>
        <td>complex64</td>
        <td>복소수, 두 개의 32비트 부동 소수점의 표현</td>
    </tr>
    <tr>
        <td>complex128</td>
        <td>복소수, 두 개의 64비트 부동 소수점의 표현</td>
    </tr> 
</table>