<h1>3장 Pandas로 데이터 가공하기</h1>

<h2>데이터 인덱싱과 선택</h2>

<b>Series:  딕셔너리</b>

In [30]:
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [31]:
data['b']

0.5

In [32]:
'a' in data

True

In [33]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [34]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [35]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

<b>Series: 1차원 배열</b>

In [36]:
# 명시적인 인덱스로 슬라이싱하기 
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [37]:
# 암묵적 정수 인덱스로 슬라이싱하기
data[0:2]

a    0.25
b    0.50
dtype: float64

In [38]:
# 마스킹
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [39]:
# 팬시 인덱싱
data[['a','e']]

a    0.25
e    1.25
dtype: float64

<b>인덱서: loc, iloc, ix</b>

In [40]:
data = pd.Series(['a','b','c'], index=[1,3,5])
data

1    a
3    b
5    c
dtype: object

In [41]:
# 인덱싱할 때 명시적인 인덱스 사용 
data[1]

'a'

In [42]:
# 슬라이싱할 때 암묵적 인덱스 사용
data[1:3]

3    b
5    c
dtype: object

In [43]:
data.loc[1]

'a'

In [44]:
data.loc[1:3]

1    a
3    b
dtype: object

In [45]:
data.iloc[1]

'b'

In [46]:
data.iloc[1:3]

3    b
5    c
dtype: object

<b>DataFrame에서 데이터 선택</b>

<b>DataFrame:  딕셔너리</b>

In [58]:
area = pd.Series({'Califonia': 423967,  'Texas': 695662,  
                  'New York': 141297,  'Florida': 170312, 'Illinois': 149995})
pop  = pd.Series({'Califonia': 38222521,'Texas': 26448193,
                  'New York': 19651127,'Florida': 19552860,'Illinois': 12882135})

data = pd.DataFrame({'area':area, 'pop':pop})

data

area       pop
Califonia  423967  38222521
Florida    170312  19552860
Illinois   149995  12882135
New York   141297  19651127
Texas      695662  26448193

In [59]:
data['area']

Califonia    423967
Florida      170312
Illinois     149995
New York     141297
Texas        695662
Name: area, dtype: int64

In [60]:
data.area

Califonia    423967
Florida      170312
Illinois     149995
New York     141297
Texas        695662
Name: area, dtype: int64

In [62]:
data.area is data['area']

True

In [63]:
data.pop is data['pop']

False

In [65]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
Califonia  423967  38222521   90.154472
Florida    170312  19552860  114.806121
Illinois   149995  12882135   85.883763
New York   141297  19651127  139.076746
Texas      695662  26448193   38.018740

<b>DataFrame: 2차원 배열</b>

In [66]:
data.values

array([[4.23967000e+05, 3.82225210e+07, 9.01544719e+01],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01]])

In [67]:
data.T

Califonia       Florida      Illinois      New York         Texas
area     4.239670e+05  1.703120e+05  1.499950e+05  1.412970e+05  6.956620e+05
pop      3.822252e+07  1.955286e+07  1.288214e+07  1.965113e+07  2.644819e+07
density  9.015447e+01  1.148061e+02  8.588376e+01  1.390767e+02  3.801874e+01

In [68]:
data.values[0]

array([4.23967000e+05, 3.82225210e+07, 9.01544719e+01])

In [69]:
data['area']

Califonia    423967
Florida      170312
Illinois     149995
New York     141297
Texas        695662
Name: area, dtype: int64

In [70]:
data.iloc[:3, :2]

area       pop
Califonia  423967  38222521
Florida    170312  19552860
Illinois   149995  12882135

In [71]:
data.loc[:'Illinois', :'pop']

area       pop
Califonia  423967  38222521
Florida    170312  19552860
Illinois   149995  12882135

In [72]:
data.ix[:3, :'pop'] # .ix is deprecated. 

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


area       pop
Califonia  423967  38222521
Florida    170312  19552860
Illinois   149995  12882135

In [73]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
Florida   19552860  114.806121
New York  19651127  139.076746

In [75]:
data.iloc[0,2] = 90
data

area       pop     density
Califonia  423967  38222521   90.000000
Florida    170312  19552860  114.806121
Illinois   149995  12882135   85.883763
New York   141297  19651127  139.076746
Texas      695662  26448193   38.018740

<b>추가적인 인덱싱 규칙</b>

In [76]:
data['Florida':'Illinois']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [77]:
data[1:3]

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [78]:
data[data.density > 100]

area       pop     density
Florida   170312  19552860  114.806121
New York  141297  19651127  139.076746

<b>Panda에서 데이터 연산하기</b>

<b>유니버설 함수: 인덱스 보존</b>

In [80]:
import pandas as pd
import numpy as np
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [84]:
df = pd.DataFrame(rng.randint(0,10, (3,4)), columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  1  7  5  1
1  4  0  9  5
2  8  0  9  2

In [85]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [88]:
np.sin(df * np.pi / 4)

A         B         C         D
0  7.071068e-01 -0.707107 -0.707107  0.707107
1  1.224647e-16  0.000000  0.707107 -0.707107
2 -2.449294e-16  0.000000  0.707107  1.000000

<b>유니버설 함수: 인덱스 정렬</b>

<b>Series에서 인덱스 정렬</b>

In [90]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662, 'Califonia': 423967}, name = 'area')
population = pd.Series({'Califonia': 38332521, 'Texas': 26448193, 'New York': 19651127}, name = 'population')

In [91]:
population / area

Alaska             NaN
Califonia    90.413926
New York           NaN
Texas        38.018740
dtype: float64

In [92]:
area.index | population.index

Index(['Alaska', 'Califonia', 'New York', 'Texas'], dtype='object')

In [94]:
A = pd.Series([2,4,6], index=[0,1,2])
B = pd.Series([1,3,5], index=[1,2,3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [95]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

<b>DataFrame에서 인덱스 정렬</b>

In [99]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)), columns=list('AB'))
A

A   B
0   8   1
1  19  14

In [100]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)), columns=list('BAC'))
B

B  A  C
0  6  7  2
1  0  3  1
2  7  3  1

In [101]:
A + B

A     B   C
0  15.0   7.0 NaN
1  22.0  14.0 NaN
2   NaN   NaN NaN

In [102]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0  15.0   7.0  12.5
1  22.0  14.0  11.5
2  13.5  17.5  11.5

<table style="width:100%">
  <tr>
    <th>파이썬 연산자</th>
    <th>Pandas 메서드</th> 
  </tr>
  <tr>
    <td>+</td>
    <td>add()</td> 
  </tr>
  <tr>
    <td>-</td>
    <td>sub(), subtract()</td> 
  </tr>
  <tr>
    <td>\*</td>
    <td>mul(), muliply()</td> 
  </tr>
  <tr>
    <td>/</td>
    <td>truediv(), div(), divide()</td> 
  </tr>
  <tr>
    <td>//</td>
    <td>floordiv()</td> 
  </tr>
  <tr>
    <td>%</td>
    <td>nod()</td> 
  </tr>
  <tr>
    <td>**</td>
    <td>pow()</td> 
  </tr>
</table>

<b>유니버설 함수: DataFrame과 Series 간의 연산</b>

In [103]:
A = rng.randint(10, size=(3,4))
A

array([[5, 5, 9, 3],
       [5, 1, 9, 1],
       [9, 3, 7, 6]])

In [104]:
A - A[0]

array([[ 0,  0,  0,  0],
       [ 0, -4,  0, -2],
       [ 4, -2, -2,  3]])

In [106]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1  0 -4  0 -2
2  4 -2 -2  3

In [107]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0  0  0  4 -2
1  4  0  8  0
2  6  0  4  3

In [108]:
halfrow = df.iloc[0, ::2]
halfrow

Q    5
S    9
Name: 0, dtype: int64

In [109]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1  0.0 NaN  0.0 NaN
2  4.0 NaN -2.0 NaN